import type { FloorMap } from './types/table.ts';

export const DEFAULT_FLOOR_ID = 'shire-main-floor';

export const DEFAULT_FLOOR_MAP: FloorMap = {
  floorId: DEFAULT_FLOOR_ID,
  mapVersion: '2026-03-07-floor-v1',
  rooms: [
    {
      roomId: 'main-dining-a',
      label: 'MAIN DINING A',
      filterLabel: 'Main Dining',
      flex: 1,
      variant: 'default',
      rows: [
        ['1', '2', '3', '4'],
        ['5', '6', '7', '8'],
        ['9', '10', '11'],
      ],
    },
    {
      roomId: 'patio',
      label: 'PATIO',
      filterLabel: 'Patio / Outside',
      flex: 0.4,
      variant: 'patio',
      rows: [
        ['P1', 'P2'],
        ['P3', 'P4'],
      ],
    },
  ],
  tables: {
    '1': {
      tableId: '1',
      tableNumber: '1',
      roomId: 'main-dining-a',
      section: 'A1',
      capacity: 4,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Maria S.',
    },
    '2': {
      tableId: '2',
      tableNumber: '2',
      roomId: 'main-dining-a',
      section: 'A1',
      capacity: 2,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Maria S.',
    },
    '3': {
      tableId: '3',
      tableNumber: '3',
      roomId: 'main-dining-a',
      section: 'A1',
      capacity: 4,
      shape: 'square',
      type: 'regular',
      assignedServer: 'Maria S.',
    },
    '4': {
      tableId: '4',
      tableNumber: '4',
      roomId: 'main-dining-a',
      section: 'A2',
      capacity: 6,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'James R.',
    },
    '5': {
      tableId: '5',
      tableNumber: '5',
      roomId: 'main-dining-a',
      section: 'A2',
      capacity: 2,
      shape: 'square',
      type: 'regular',
      assignedServer: 'James R.',
    },
    '6': {
      tableId: '6',
      tableNumber: '6',
      roomId: 'main-dining-a',
      section: 'A2',
      capacity: 4,
      shape: 'square',
      type: 'regular',
      assignedServer: 'James R.',
    },
    '7': {
      tableId: '7',
      tableNumber: '7',
      roomId: 'main-dining-a',
      section: 'A3',
      capacity: 2,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Maria S.',
    },
    '8': {
      tableId: '8',
      tableNumber: '8',
      roomId: 'main-dining-a',
      section: 'A3',
      capacity: 4,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Maria S.',
    },
    '9': {
      tableId: '9',
      tableNumber: '9',
      roomId: 'main-dining-a',
      section: 'A4',
      capacity: 8,
      shape: 'horizontal',
      type: 'booth',
      assignedServer: 'Alex T.',
    },
    '10': {
      tableId: '10',
      tableNumber: '10',
      roomId: 'main-dining-a',
      section: 'A4',
      capacity: 2,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Alex T.',
    },
    '11': {
      tableId: '11',
      tableNumber: '11',
      roomId: 'main-dining-a',
      section: 'A4',
      capacity: 4,
      shape: 'circle',
      type: 'regular',
      assignedServer: 'Alex T.',
    },
    P1: {
      tableId: 'P1',
      tableNumber: 'P1',
      roomId: 'patio',
      section: 'P1',
      capacity: 4,
      shape: 'square',
      type: 'outdoor',
      assignedServer: 'Nina W.',
    },
    P2: {
      tableId: 'P2',
      tableNumber: 'P2',
      roomId: 'patio',
      section: 'P1',
      capacity: 4,
      shape: 'square',
      type: 'outdoor',
      assignedServer: 'Nina W.',
    },
    P3: {
      tableId: 'P3',
      tableNumber: 'P3',
      roomId: 'patio',
      section: 'P2',
      capacity: 4,
      shape: 'square',
      type: 'outdoor',
      assignedServer: 'Nina W.',
    },
    P4: {
      tableId: 'P4',
      tableNumber: 'P4',
      roomId: 'patio',
      section: 'P2',
      capacity: 2,
      shape: 'square',
      type: 'outdoor',
      assignedServer: 'Nina W.',
    },
  },
};
